version: 0.2
phases:
  pre_build:
    commands:
      - echo "========================="
      - echo "Installing dependencies..."
      - echo "========================="
      - apt update && apt install -y curl python-pip
      - pip install awscli --upgrade
      - aws s3 cp s3://danielhartnell/kubeconfig /tmp/kubeconfig
      - curl -O https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/bin/kubectl
      - curl -O https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/bin/linux/amd64/heptio-authenticator-aws
      - chmod +x heptio-authenticator-aws
      - mv heptio-authenticator-aws /usr/bin/heptio-authenticator-aws
      - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - echo "========================="
      - echo "Setting environment variables..."
      - echo "========================="
      - COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - ACCOUNT_ID=`echo $CODEBUILD_BUILD_ARN | awk -F ':' '{print $5}'`
      - SERVICE_NAME=test-eks
      - EKS_CLUSTER=eks-development
      - echo "========================="
      - echo "Logging in to Amazon ECR..."
      - echo "========================="
      - aws ecr get-login --region ${AWS_REGION} --no-include-email | bash

  build:
    commands:
      - echo "========================="
      - echo "Starting build..."
      - echo "========================="
      - docker build -t ${SERVICE_NAME} .
      - docker tag test-eks ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${SERVICE_NAME}:$COMMIT_SHA
      - echo "========================="
      - echo "Scanning container image with CoreOS Clair"
      - echo "========================="
      - docker run -d --name db arminc/clair-db:latest
      - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.3
      - sleep 10
      - curl -L -O https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
      - chmod +x clair-scanner_linux_amd64
      - ./clair-scanner_linux_amd64 --ip=172.18.0.1 ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${SERVICE_NAME}:$COMMIT_SHA

  post_build:
    commands:
      - echo "========================="
      - echo "Pushing image to registry..."
      - echo "========================="
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${SERVICE_NAME}:$COMMIT_SHA
      - echo "========================="
      - echo "Running deployment to development cluster..."
      - echo "========================="
      - /usr/local/bin/helm template kubernetes --set name=helloworld,commit=${COMMIT_SHA} --set-string account_id=${ACCOUNT_ID} | /usr/bin/kubectl --kubeconfig=/tmp/kubeconfig apply -f -
