---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: webdev
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}-web
          image: {{ .Values.account_id }}.dkr.ecr.us-west-2.amazonaws.com/test-eks:v5
          ports:
            - containerPort: 8080
