---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}-service
  namespace: webdev
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
