---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: webdev
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-web
          image: 787367611277.dkr.ecr.us-west-2.amazonaws.com/test-eks:v4
          ports:
            - containerPort: 8080
