---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-web
          image: k8s.gcr.io/echoserver:1.4
          ports:
            - containerPort: 8080
